INSERT INTO Question (question, type) VALUES ('Q1 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q2 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q3 - B', 'AR');
INSERT INTO Question (question, type) VALUES ('Q4 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q5 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q6 - C', 'AR');
INSERT INTO Question (question, type) VALUES ('Q7 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q8 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q9 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q10 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q11 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q12 - D', 'AR');
INSERT INTO Question (question, type) VALUES ('Q13 - B', 'AR');
INSERT INTO Question (question, type) VALUES ('Q14 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q15 - B', 'AR');
INSERT INTO Question (question, type) VALUES ('Q16 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q17 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q18 - C', 'AR');
INSERT INTO Question (question, type) VALUES ('Q19 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q20 - C', 'AR');
INSERT INTO Question (question, type) VALUES ('Q21 - B', 'AR');
INSERT INTO Question (question, type) VALUES ('Q22 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q23 - D', 'AR');
INSERT INTO Question (question, type) VALUES ('Q24 - D', 'AR');
INSERT INTO Question (question, type) VALUES ('Q25 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q26 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q27 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q28 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q29 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q30 - A', 'AR');
INSERT INTO Question (question, type) VALUES ('Q31 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q32 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q33 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q34 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q35 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q36 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q37 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q38 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q39 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q40 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q41 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q42 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q43 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q44 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q45 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q46 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q47 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q48 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q49 - A', 'SR');
INSERT INTO Question (question, type) VALUES ('Q50 - A', 'SR');

INSERT INTO Answer (id, correct, answer) VALUES (1, 1, '_A_');
INSERT INTO Answer (id, correct, answer) VALUES (2, 0, '_B_');
INSERT INTO Answer (id, correct, answer) VALUES (3, 0, '_C_');
INSERT INTO Answer (id, correct, answer) VALUES (4, 0, '_D_');

INSERT INTO QuestionsAnswer VALUES (1, 1);
INSERT INTO QuestionsAnswer VALUES (1, 2);
INSERT INTO QuestionsAnswer VALUES (1, 3);
INSERT INTO QuestionsAnswer VALUES (1, 4);
INSERT INTO QuestionsAnswer VALUES (2, 1);
INSERT INTO QuestionsAnswer VALUES (2, 2);
INSERT INTO QuestionsAnswer VALUES (2, 3);
INSERT INTO QuestionsAnswer VALUES (2, 4);
INSERT INTO QuestionsAnswer VALUES (3, 1);
INSERT INTO QuestionsAnswer VALUES (3, 2);
INSERT INTO QuestionsAnswer VALUES (3, 3);
INSERT INTO QuestionsAnswer VALUES (3, 4);
INSERT INTO QuestionsAnswer VALUES (4, 1);
INSERT INTO QuestionsAnswer VALUES (4, 2);
INSERT INTO QuestionsAnswer VALUES (4, 3);
INSERT INTO QuestionsAnswer VALUES (4, 4);
INSERT INTO QuestionsAnswer VALUES (5, 1);
INSERT INTO QuestionsAnswer VALUES (5, 2);
INSERT INTO QuestionsAnswer VALUES (5, 3);
INSERT INTO QuestionsAnswer VALUES (5, 4);
INSERT INTO QuestionsAnswer VALUES (6, 1);
INSERT INTO QuestionsAnswer VALUES (6, 2);
INSERT INTO QuestionsAnswer VALUES (6, 3);
INSERT INTO QuestionsAnswer VALUES (6, 4);
INSERT INTO QuestionsAnswer VALUES (7, 1);
INSERT INTO QuestionsAnswer VALUES (7, 2);
INSERT INTO QuestionsAnswer VALUES (7, 3);
INSERT INTO QuestionsAnswer VALUES (7, 4);
INSERT INTO QuestionsAnswer VALUES (8, 1);
INSERT INTO QuestionsAnswer VALUES (8, 2);
INSERT INTO QuestionsAnswer VALUES (8, 3);
INSERT INTO QuestionsAnswer VALUES (8, 4);
INSERT INTO QuestionsAnswer VALUES (9, 1);
INSERT INTO QuestionsAnswer VALUES (9, 2);
INSERT INTO QuestionsAnswer VALUES (9, 3);
INSERT INTO QuestionsAnswer VALUES (9, 4);
INSERT INTO QuestionsAnswer VALUES (10, 1);
INSERT INTO QuestionsAnswer VALUES (10, 2);
INSERT INTO QuestionsAnswer VALUES (10, 3);
INSERT INTO QuestionsAnswer VALUES (10, 4);
INSERT INTO QuestionsAnswer VALUES (11, 1);
INSERT INTO QuestionsAnswer VALUES (11, 2);
INSERT INTO QuestionsAnswer VALUES (11, 3);
INSERT INTO QuestionsAnswer VALUES (11, 4);
INSERT INTO QuestionsAnswer VALUES (12, 1);
INSERT INTO QuestionsAnswer VALUES (12, 2);
INSERT INTO QuestionsAnswer VALUES (12, 3);
INSERT INTO QuestionsAnswer VALUES (12, 4);
INSERT INTO QuestionsAnswer VALUES (13, 1);
INSERT INTO QuestionsAnswer VALUES (13, 2);
INSERT INTO QuestionsAnswer VALUES (13, 3);
INSERT INTO QuestionsAnswer VALUES (13, 4);
INSERT INTO QuestionsAnswer VALUES (14, 1);
INSERT INTO QuestionsAnswer VALUES (14, 2);
INSERT INTO QuestionsAnswer VALUES (14, 3);
INSERT INTO QuestionsAnswer VALUES (14, 4);
INSERT INTO QuestionsAnswer VALUES (15, 1);
INSERT INTO QuestionsAnswer VALUES (15, 2);
INSERT INTO QuestionsAnswer VALUES (15, 3);
INSERT INTO QuestionsAnswer VALUES (15, 4);
INSERT INTO QuestionsAnswer VALUES (16, 1);
INSERT INTO QuestionsAnswer VALUES (16, 2);
INSERT INTO QuestionsAnswer VALUES (16, 3);
INSERT INTO QuestionsAnswer VALUES (16, 4);
INSERT INTO QuestionsAnswer VALUES (17, 1);
INSERT INTO QuestionsAnswer VALUES (17, 2);
INSERT INTO QuestionsAnswer VALUES (17, 3);
INSERT INTO QuestionsAnswer VALUES (17, 4);
INSERT INTO QuestionsAnswer VALUES (18, 1);
INSERT INTO QuestionsAnswer VALUES (18, 2);
INSERT INTO QuestionsAnswer VALUES (18, 3);
INSERT INTO QuestionsAnswer VALUES (18, 4);
INSERT INTO QuestionsAnswer VALUES (19, 1);
INSERT INTO QuestionsAnswer VALUES (19, 2);
INSERT INTO QuestionsAnswer VALUES (19, 3);
INSERT INTO QuestionsAnswer VALUES (19, 4);
INSERT INTO QuestionsAnswer VALUES (20, 1);
INSERT INTO QuestionsAnswer VALUES (20, 2);
INSERT INTO QuestionsAnswer VALUES (20, 3);
INSERT INTO QuestionsAnswer VALUES (20, 4);
INSERT INTO QuestionsAnswer VALUES (21, 1);
INSERT INTO QuestionsAnswer VALUES (21, 2);
INSERT INTO QuestionsAnswer VALUES (21, 3);
INSERT INTO QuestionsAnswer VALUES (21, 4);
INSERT INTO QuestionsAnswer VALUES (22, 1);
INSERT INTO QuestionsAnswer VALUES (22, 2);
INSERT INTO QuestionsAnswer VALUES (22, 3);
INSERT INTO QuestionsAnswer VALUES (22, 4);
INSERT INTO QuestionsAnswer VALUES (23, 1);
INSERT INTO QuestionsAnswer VALUES (23, 2);
INSERT INTO QuestionsAnswer VALUES (23, 3);
INSERT INTO QuestionsAnswer VALUES (23, 4);
INSERT INTO QuestionsAnswer VALUES (24, 1);
INSERT INTO QuestionsAnswer VALUES (24, 2);
INSERT INTO QuestionsAnswer VALUES (24, 3);
INSERT INTO QuestionsAnswer VALUES (24, 4);
INSERT INTO QuestionsAnswer VALUES (25, 1);
INSERT INTO QuestionsAnswer VALUES (25, 2);
INSERT INTO QuestionsAnswer VALUES (25, 3);
INSERT INTO QuestionsAnswer VALUES (25, 4);
INSERT INTO QuestionsAnswer VALUES (26, 1);
INSERT INTO QuestionsAnswer VALUES (26, 2);
INSERT INTO QuestionsAnswer VALUES (26, 3);
INSERT INTO QuestionsAnswer VALUES (26, 4);
INSERT INTO QuestionsAnswer VALUES (27, 1);
INSERT INTO QuestionsAnswer VALUES (27, 2);
INSERT INTO QuestionsAnswer VALUES (27, 3);
INSERT INTO QuestionsAnswer VALUES (27, 4);
INSERT INTO QuestionsAnswer VALUES (28, 1);
INSERT INTO QuestionsAnswer VALUES (28, 2);
INSERT INTO QuestionsAnswer VALUES (28, 3);
INSERT INTO QuestionsAnswer VALUES (28, 4);
INSERT INTO QuestionsAnswer VALUES (29, 1);
INSERT INTO QuestionsAnswer VALUES (29, 2);
INSERT INTO QuestionsAnswer VALUES (29, 3);
INSERT INTO QuestionsAnswer VALUES (29, 4);
INSERT INTO QuestionsAnswer VALUES (30, 1);
INSERT INTO QuestionsAnswer VALUES (30, 2);
INSERT INTO QuestionsAnswer VALUES (30, 3);
INSERT INTO QuestionsAnswer VALUES (30, 4);
INSERT INTO QuestionsAnswer VALUES (31, 1);
INSERT INTO QuestionsAnswer VALUES (31, 2);
INSERT INTO QuestionsAnswer VALUES (31, 3);
INSERT INTO QuestionsAnswer VALUES (31, 4);
INSERT INTO QuestionsAnswer VALUES (32, 1);
INSERT INTO QuestionsAnswer VALUES (32, 2);
INSERT INTO QuestionsAnswer VALUES (32, 3);
INSERT INTO QuestionsAnswer VALUES (32, 4);
INSERT INTO QuestionsAnswer VALUES (33, 1);
INSERT INTO QuestionsAnswer VALUES (33, 2);
INSERT INTO QuestionsAnswer VALUES (33, 3);
INSERT INTO QuestionsAnswer VALUES (33, 4);
INSERT INTO QuestionsAnswer VALUES (34, 1);
INSERT INTO QuestionsAnswer VALUES (34, 2);
INSERT INTO QuestionsAnswer VALUES (34, 3);
INSERT INTO QuestionsAnswer VALUES (34, 4);
INSERT INTO QuestionsAnswer VALUES (35, 1);
INSERT INTO QuestionsAnswer VALUES (35, 2);
INSERT INTO QuestionsAnswer VALUES (35, 3);
INSERT INTO QuestionsAnswer VALUES (35, 4);
INSERT INTO QuestionsAnswer VALUES (36, 1);
INSERT INTO QuestionsAnswer VALUES (36, 2);
INSERT INTO QuestionsAnswer VALUES (36, 3);
INSERT INTO QuestionsAnswer VALUES (36, 4);
INSERT INTO QuestionsAnswer VALUES (37, 1);
INSERT INTO QuestionsAnswer VALUES (37, 2);
INSERT INTO QuestionsAnswer VALUES (37, 3);
INSERT INTO QuestionsAnswer VALUES (37, 4);
INSERT INTO QuestionsAnswer VALUES (38, 1);
INSERT INTO QuestionsAnswer VALUES (38, 2);
INSERT INTO QuestionsAnswer VALUES (38, 3);
INSERT INTO QuestionsAnswer VALUES (38, 4);
INSERT INTO QuestionsAnswer VALUES (39, 1);
INSERT INTO QuestionsAnswer VALUES (39, 2);
INSERT INTO QuestionsAnswer VALUES (39, 3);
INSERT INTO QuestionsAnswer VALUES (39, 4);
INSERT INTO QuestionsAnswer VALUES (40, 1);
INSERT INTO QuestionsAnswer VALUES (40, 2);
INSERT INTO QuestionsAnswer VALUES (40, 3);
INSERT INTO QuestionsAnswer VALUES (40, 4);
INSERT INTO QuestionsAnswer VALUES (41, 1);
INSERT INTO QuestionsAnswer VALUES (41, 2);
INSERT INTO QuestionsAnswer VALUES (41, 3);
INSERT INTO QuestionsAnswer VALUES (41, 4);
INSERT INTO QuestionsAnswer VALUES (42, 1);
INSERT INTO QuestionsAnswer VALUES (42, 2);
INSERT INTO QuestionsAnswer VALUES (42, 3);
INSERT INTO QuestionsAnswer VALUES (42, 4);
INSERT INTO QuestionsAnswer VALUES (43, 1);
INSERT INTO QuestionsAnswer VALUES (43, 2);
INSERT INTO QuestionsAnswer VALUES (43, 3);
INSERT INTO QuestionsAnswer VALUES (43, 4);
INSERT INTO QuestionsAnswer VALUES (44, 1);
INSERT INTO QuestionsAnswer VALUES (44, 2);
INSERT INTO QuestionsAnswer VALUES (44, 3);
INSERT INTO QuestionsAnswer VALUES (44, 4);
INSERT INTO QuestionsAnswer VALUES (45, 1);
INSERT INTO QuestionsAnswer VALUES (45, 2);
INSERT INTO QuestionsAnswer VALUES (45, 3);
INSERT INTO QuestionsAnswer VALUES (45, 4);
INSERT INTO QuestionsAnswer VALUES (46, 1);
INSERT INTO QuestionsAnswer VALUES (46, 2);
INSERT INTO QuestionsAnswer VALUES (46, 3);
INSERT INTO QuestionsAnswer VALUES (46, 4);
INSERT INTO QuestionsAnswer VALUES (47, 1);
INSERT INTO QuestionsAnswer VALUES (47, 2);
INSERT INTO QuestionsAnswer VALUES (47, 3);
INSERT INTO QuestionsAnswer VALUES (47, 4);
INSERT INTO QuestionsAnswer VALUES (48, 1);
INSERT INTO QuestionsAnswer VALUES (48, 2);
INSERT INTO QuestionsAnswer VALUES (48, 3);
INSERT INTO QuestionsAnswer VALUES (48, 4);
INSERT INTO QuestionsAnswer VALUES (49, 1);
INSERT INTO QuestionsAnswer VALUES (49, 2);
INSERT INTO QuestionsAnswer VALUES (49, 3);
INSERT INTO QuestionsAnswer VALUES (49, 4);
INSERT INTO QuestionsAnswer VALUES (50, 1);
INSERT INTO QuestionsAnswer VALUES (50, 2);
INSERT INTO QuestionsAnswer VALUES (50, 3);
INSERT INTO QuestionsAnswer VALUES (50, 4);