INSERT INTO Question (id, question, type) VALUES (1,'Pytanie o <span class="blue">Niebieskiego Pałkarza</span>.', 'AR');
INSERT INTO Question (id, question, type) VALUES (2,'Długie pytanie zawierające dużo różnych słów, aczkolwiek nie jest ono gramatycznie poprawne, więc nie kierujmy się jego wartością językową. Równie dobrze mogłem użyć lorem ipsum, God Damn It!', 'AR');
INSERT INTO Question (id, question, type) VALUES (3,'Pytanie o <span class="red">Czerwonego Pałkarza</span> oraz o <span class="blue">Niebieskiego Ścigającego</span>.', 'AR');
INSERT INTO Question (id, question, type) VALUES (4,'Które z poniższych pytań <span class="bold">nie</span> zawiera formatowania?', 'AR');
INSERT INTO Question (id, question, type) VALUES (5,'Q5 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (6,'Q6 - C', 'AR');
INSERT INTO Question (id, question, type) VALUES (7,'Q7 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (8,'Q8 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (9,'Q9 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (10,'Q10 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (11,'Q11 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (12,'Q12 - D', 'AR');
INSERT INTO Question (id, question, type) VALUES (13,'Q13 - B', 'AR');
INSERT INTO Question (id, question, type) VALUES (14,'Q14 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (15,'Q15 - B', 'AR');
INSERT INTO Question (id, question, type) VALUES (16,'Q16 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (17,'Q17 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (18,'Q18 - C', 'AR');
INSERT INTO Question (id, question, type) VALUES (19,'Q19 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (20,'Q20 - C', 'AR');
INSERT INTO Question (id, question, type) VALUES (21,'Q21 - B', 'AR');
INSERT INTO Question (id, question, type) VALUES (22,'Q22 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (23,'Q23 - D', 'AR');
INSERT INTO Question (id, question, type) VALUES (24,'Q24 - D', 'AR');
INSERT INTO Question (id, question, type) VALUES (25,'Q25 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (26,'Q26 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (27,'Q27 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (28,'Q28 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (29,'Q29 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (30,'Q30 - A', 'AR');
INSERT INTO Question (id, question, type) VALUES (31,'Q31 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (32,'Q32 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (33,'Q33 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (34,'Q34 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (35,'Q35 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (36,'Q36 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (37,'Q37 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (38,'Q38 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (39,'Q39 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (40,'Q40 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (41,'Q41 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (42,'Q42 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (43,'Q43 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (44,'Q44 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (45,'Q45 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (46,'Q46 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (47,'Q47 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (48,'Q48 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (49,'Q49 - A', 'SR');
INSERT INTO Question (id, question, type) VALUES (50,'Q50 - A', 'SR');

INSERT INTO Answer (id, correct, answer) VALUES (1, 1, 'Krótka odpowiedź, poprawna');
INSERT INTO Answer (id, correct, answer) VALUES (2, 0, 'Krótka zła odpowiedź');
INSERT INTO Answer (id, correct, answer) VALUES (3, 0, 'Długa odpowiedź, zawierająca dużo mało interesujących słów. Generalnie za takie odpowiedzi wirtualny sędzia dostałby niebieską kartkę, #YOLO. Może niech jeszcze ciut się przedłuży, lol. Wgl nwm już o czym miałem tu pisać, hehe.');
INSERT INTO Answer (id, correct, answer) VALUES (4, 0, 'I to takie inne pytanie.');

INSERT INTO QuestionsAnswer VALUES (1, 1);
INSERT INTO QuestionsAnswer VALUES (1, 2);
INSERT INTO QuestionsAnswer VALUES (1, 3);
INSERT INTO QuestionsAnswer VALUES (1, 4);
INSERT INTO QuestionsAnswer VALUES (2, 1);
INSERT INTO QuestionsAnswer VALUES (2, 2);
INSERT INTO QuestionsAnswer VALUES (2, 3);
INSERT INTO QuestionsAnswer VALUES (2, 4);
INSERT INTO QuestionsAnswer VALUES (3, 1);
INSERT INTO QuestionsAnswer VALUES (3, 2);
INSERT INTO QuestionsAnswer VALUES (3, 3);
INSERT INTO QuestionsAnswer VALUES (3, 4);
INSERT INTO QuestionsAnswer VALUES (4, 1);
INSERT INTO QuestionsAnswer VALUES (4, 2);
INSERT INTO QuestionsAnswer VALUES (4, 3);
INSERT INTO QuestionsAnswer VALUES (4, 4);
INSERT INTO QuestionsAnswer VALUES (5, 1);
INSERT INTO QuestionsAnswer VALUES (5, 2);
INSERT INTO QuestionsAnswer VALUES (5, 3);
INSERT INTO QuestionsAnswer VALUES (5, 4);
INSERT INTO QuestionsAnswer VALUES (6, 1);
INSERT INTO QuestionsAnswer VALUES (6, 2);
INSERT INTO QuestionsAnswer VALUES (6, 3);
INSERT INTO QuestionsAnswer VALUES (6, 4);
INSERT INTO QuestionsAnswer VALUES (7, 1);
INSERT INTO QuestionsAnswer VALUES (7, 2);
INSERT INTO QuestionsAnswer VALUES (7, 3);
INSERT INTO QuestionsAnswer VALUES (7, 4);
INSERT INTO QuestionsAnswer VALUES (8, 1);
INSERT INTO QuestionsAnswer VALUES (8, 2);
INSERT INTO QuestionsAnswer VALUES (8, 3);
INSERT INTO QuestionsAnswer VALUES (8, 4);
INSERT INTO QuestionsAnswer VALUES (9, 1);
INSERT INTO QuestionsAnswer VALUES (9, 2);
INSERT INTO QuestionsAnswer VALUES (9, 3);
INSERT INTO QuestionsAnswer VALUES (9, 4);
INSERT INTO QuestionsAnswer VALUES (10, 1);
INSERT INTO QuestionsAnswer VALUES (10, 2);
INSERT INTO QuestionsAnswer VALUES (10, 3);
INSERT INTO QuestionsAnswer VALUES (10, 4);
INSERT INTO QuestionsAnswer VALUES (11, 1);
INSERT INTO QuestionsAnswer VALUES (11, 2);
INSERT INTO QuestionsAnswer VALUES (11, 3);
INSERT INTO QuestionsAnswer VALUES (11, 4);
INSERT INTO QuestionsAnswer VALUES (12, 1);
INSERT INTO QuestionsAnswer VALUES (12, 2);
INSERT INTO QuestionsAnswer VALUES (12, 3);
INSERT INTO QuestionsAnswer VALUES (12, 4);
INSERT INTO QuestionsAnswer VALUES (13, 1);
INSERT INTO QuestionsAnswer VALUES (13, 2);
INSERT INTO QuestionsAnswer VALUES (13, 3);
INSERT INTO QuestionsAnswer VALUES (13, 4);
INSERT INTO QuestionsAnswer VALUES (14, 1);
INSERT INTO QuestionsAnswer VALUES (14, 2);
INSERT INTO QuestionsAnswer VALUES (14, 3);
INSERT INTO QuestionsAnswer VALUES (14, 4);
INSERT INTO QuestionsAnswer VALUES (15, 1);
INSERT INTO QuestionsAnswer VALUES (15, 2);
INSERT INTO QuestionsAnswer VALUES (15, 3);
INSERT INTO QuestionsAnswer VALUES (15, 4);
INSERT INTO QuestionsAnswer VALUES (16, 1);
INSERT INTO QuestionsAnswer VALUES (16, 2);
INSERT INTO QuestionsAnswer VALUES (16, 3);
INSERT INTO QuestionsAnswer VALUES (16, 4);
INSERT INTO QuestionsAnswer VALUES (17, 1);
INSERT INTO QuestionsAnswer VALUES (17, 2);
INSERT INTO QuestionsAnswer VALUES (17, 3);
INSERT INTO QuestionsAnswer VALUES (17, 4);
INSERT INTO QuestionsAnswer VALUES (18, 1);
INSERT INTO QuestionsAnswer VALUES (18, 2);
INSERT INTO QuestionsAnswer VALUES (18, 3);
INSERT INTO QuestionsAnswer VALUES (18, 4);
INSERT INTO QuestionsAnswer VALUES (19, 1);
INSERT INTO QuestionsAnswer VALUES (19, 2);
INSERT INTO QuestionsAnswer VALUES (19, 3);
INSERT INTO QuestionsAnswer VALUES (19, 4);
INSERT INTO QuestionsAnswer VALUES (20, 1);
INSERT INTO QuestionsAnswer VALUES (20, 2);
INSERT INTO QuestionsAnswer VALUES (20, 3);
INSERT INTO QuestionsAnswer VALUES (20, 4);
INSERT INTO QuestionsAnswer VALUES (21, 1);
INSERT INTO QuestionsAnswer VALUES (21, 2);
INSERT INTO QuestionsAnswer VALUES (21, 3);
INSERT INTO QuestionsAnswer VALUES (21, 4);
INSERT INTO QuestionsAnswer VALUES (22, 1);
INSERT INTO QuestionsAnswer VALUES (22, 2);
INSERT INTO QuestionsAnswer VALUES (22, 3);
INSERT INTO QuestionsAnswer VALUES (22, 4);
INSERT INTO QuestionsAnswer VALUES (23, 1);
INSERT INTO QuestionsAnswer VALUES (23, 2);
INSERT INTO QuestionsAnswer VALUES (23, 3);
INSERT INTO QuestionsAnswer VALUES (23, 4);
INSERT INTO QuestionsAnswer VALUES (24, 1);
INSERT INTO QuestionsAnswer VALUES (24, 2);
INSERT INTO QuestionsAnswer VALUES (24, 3);
INSERT INTO QuestionsAnswer VALUES (24, 4);
INSERT INTO QuestionsAnswer VALUES (25, 1);
INSERT INTO QuestionsAnswer VALUES (25, 2);
INSERT INTO QuestionsAnswer VALUES (25, 3);
INSERT INTO QuestionsAnswer VALUES (25, 4);
INSERT INTO QuestionsAnswer VALUES (26, 1);
INSERT INTO QuestionsAnswer VALUES (26, 2);
INSERT INTO QuestionsAnswer VALUES (26, 3);
INSERT INTO QuestionsAnswer VALUES (26, 4);
INSERT INTO QuestionsAnswer VALUES (27, 1);
INSERT INTO QuestionsAnswer VALUES (27, 2);
INSERT INTO QuestionsAnswer VALUES (27, 3);
INSERT INTO QuestionsAnswer VALUES (27, 4);
INSERT INTO QuestionsAnswer VALUES (28, 1);
INSERT INTO QuestionsAnswer VALUES (28, 2);
INSERT INTO QuestionsAnswer VALUES (28, 3);
INSERT INTO QuestionsAnswer VALUES (28, 4);
INSERT INTO QuestionsAnswer VALUES (29, 1);
INSERT INTO QuestionsAnswer VALUES (29, 2);
INSERT INTO QuestionsAnswer VALUES (29, 3);
INSERT INTO QuestionsAnswer VALUES (29, 4);
INSERT INTO QuestionsAnswer VALUES (30, 1);
INSERT INTO QuestionsAnswer VALUES (30, 2);
INSERT INTO QuestionsAnswer VALUES (30, 3);
INSERT INTO QuestionsAnswer VALUES (30, 4);
INSERT INTO QuestionsAnswer VALUES (31, 1);
INSERT INTO QuestionsAnswer VALUES (31, 2);
INSERT INTO QuestionsAnswer VALUES (31, 3);
INSERT INTO QuestionsAnswer VALUES (31, 4);
INSERT INTO QuestionsAnswer VALUES (32, 1);
INSERT INTO QuestionsAnswer VALUES (32, 2);
INSERT INTO QuestionsAnswer VALUES (32, 3);
INSERT INTO QuestionsAnswer VALUES (32, 4);
INSERT INTO QuestionsAnswer VALUES (33, 1);
INSERT INTO QuestionsAnswer VALUES (33, 2);
INSERT INTO QuestionsAnswer VALUES (33, 3);
INSERT INTO QuestionsAnswer VALUES (33, 4);
INSERT INTO QuestionsAnswer VALUES (34, 1);
INSERT INTO QuestionsAnswer VALUES (34, 2);
INSERT INTO QuestionsAnswer VALUES (34, 3);
INSERT INTO QuestionsAnswer VALUES (34, 4);
INSERT INTO QuestionsAnswer VALUES (35, 1);
INSERT INTO QuestionsAnswer VALUES (35, 2);
INSERT INTO QuestionsAnswer VALUES (35, 3);
INSERT INTO QuestionsAnswer VALUES (35, 4);
INSERT INTO QuestionsAnswer VALUES (36, 1);
INSERT INTO QuestionsAnswer VALUES (36, 2);
INSERT INTO QuestionsAnswer VALUES (36, 3);
INSERT INTO QuestionsAnswer VALUES (36, 4);
INSERT INTO QuestionsAnswer VALUES (37, 1);
INSERT INTO QuestionsAnswer VALUES (37, 2);
INSERT INTO QuestionsAnswer VALUES (37, 3);
INSERT INTO QuestionsAnswer VALUES (37, 4);
INSERT INTO QuestionsAnswer VALUES (38, 1);
INSERT INTO QuestionsAnswer VALUES (38, 2);
INSERT INTO QuestionsAnswer VALUES (38, 3);
INSERT INTO QuestionsAnswer VALUES (38, 4);
INSERT INTO QuestionsAnswer VALUES (39, 1);
INSERT INTO QuestionsAnswer VALUES (39, 2);
INSERT INTO QuestionsAnswer VALUES (39, 3);
INSERT INTO QuestionsAnswer VALUES (39, 4);
INSERT INTO QuestionsAnswer VALUES (40, 1);
INSERT INTO QuestionsAnswer VALUES (40, 2);
INSERT INTO QuestionsAnswer VALUES (40, 3);
INSERT INTO QuestionsAnswer VALUES (40, 4);
INSERT INTO QuestionsAnswer VALUES (41, 1);
INSERT INTO QuestionsAnswer VALUES (41, 2);
INSERT INTO QuestionsAnswer VALUES (41, 3);
INSERT INTO QuestionsAnswer VALUES (41, 4);
INSERT INTO QuestionsAnswer VALUES (42, 1);
INSERT INTO QuestionsAnswer VALUES (42, 2);
INSERT INTO QuestionsAnswer VALUES (42, 3);
INSERT INTO QuestionsAnswer VALUES (42, 4);
INSERT INTO QuestionsAnswer VALUES (43, 1);
INSERT INTO QuestionsAnswer VALUES (43, 2);
INSERT INTO QuestionsAnswer VALUES (43, 3);
INSERT INTO QuestionsAnswer VALUES (43, 4);
INSERT INTO QuestionsAnswer VALUES (44, 1);
INSERT INTO QuestionsAnswer VALUES (44, 2);
INSERT INTO QuestionsAnswer VALUES (44, 3);
INSERT INTO QuestionsAnswer VALUES (44, 4);
INSERT INTO QuestionsAnswer VALUES (45, 1);
INSERT INTO QuestionsAnswer VALUES (45, 2);
INSERT INTO QuestionsAnswer VALUES (45, 3);
INSERT INTO QuestionsAnswer VALUES (45, 4);
INSERT INTO QuestionsAnswer VALUES (46, 1);
INSERT INTO QuestionsAnswer VALUES (46, 2);
INSERT INTO QuestionsAnswer VALUES (46, 3);
INSERT INTO QuestionsAnswer VALUES (46, 4);
INSERT INTO QuestionsAnswer VALUES (47, 1);
INSERT INTO QuestionsAnswer VALUES (47, 2);
INSERT INTO QuestionsAnswer VALUES (47, 3);
INSERT INTO QuestionsAnswer VALUES (47, 4);
INSERT INTO QuestionsAnswer VALUES (48, 1);
INSERT INTO QuestionsAnswer VALUES (48, 2);
INSERT INTO QuestionsAnswer VALUES (48, 3);
INSERT INTO QuestionsAnswer VALUES (48, 4);
INSERT INTO QuestionsAnswer VALUES (49, 1);
INSERT INTO QuestionsAnswer VALUES (49, 2);
INSERT INTO QuestionsAnswer VALUES (49, 3);
INSERT INTO QuestionsAnswer VALUES (49, 4);
INSERT INTO QuestionsAnswer VALUES (50, 1);
INSERT INTO QuestionsAnswer VALUES (50, 2);
INSERT INTO QuestionsAnswer VALUES (50, 3);
INSERT INTO QuestionsAnswer VALUES (50, 4);